/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ExecutiveShieldRouteImport } from './routes/executive-shield'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesUaeGratuityCalculationRouteImport } from './routes/guides.uae-gratuity-calculation'
import { Route as GuidesFreeZoneEmploymentLawRouteImport } from './routes/guides.free-zone-employment-law'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveShieldRoute = ExecutiveShieldRouteImport.update({
  id: '/executive-shield',
  path: '/executive-shield',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesUaeGratuityCalculationRoute =
  GuidesUaeGratuityCalculationRouteImport.update({
    id: '/guides/uae-gratuity-calculation',
    path: '/guides/uae-gratuity-calculation',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesFreeZoneEmploymentLawRoute =
  GuidesFreeZoneEmploymentLawRouteImport.update({
    id: '/guides/free-zone-employment-law',
    path: '/guides/free-zone-employment-law',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/executive-shield': typeof ExecutiveShieldRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guides/free-zone-employment-law': typeof GuidesFreeZoneEmploymentLawRoute
  '/guides/uae-gratuity-calculation': typeof GuidesUaeGratuityCalculationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/executive-shield': typeof ExecutiveShieldRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guides/free-zone-employment-law': typeof GuidesFreeZoneEmploymentLawRoute
  '/guides/uae-gratuity-calculation': typeof GuidesUaeGratuityCalculationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/executive-shield': typeof ExecutiveShieldRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guides/free-zone-employment-law': typeof GuidesFreeZoneEmploymentLawRoute
  '/guides/uae-gratuity-calculation': typeof GuidesUaeGratuityCalculationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/checkout'
    | '/contact'
    | '/executive-shield'
    | '/privacy'
    | '/terms'
    | '/guides/free-zone-employment-law'
    | '/guides/uae-gratuity-calculation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/checkout'
    | '/contact'
    | '/executive-shield'
    | '/privacy'
    | '/terms'
    | '/guides/free-zone-employment-law'
    | '/guides/uae-gratuity-calculation'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/checkout'
    | '/contact'
    | '/executive-shield'
    | '/privacy'
    | '/terms'
    | '/guides/free-zone-employment-law'
    | '/guides/uae-gratuity-calculation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ExecutiveShieldRoute: typeof ExecutiveShieldRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  GuidesFreeZoneEmploymentLawRoute: typeof GuidesFreeZoneEmploymentLawRoute
  GuidesUaeGratuityCalculationRoute: typeof GuidesUaeGratuityCalculationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-shield': {
      id: '/executive-shield'
      path: '/executive-shield'
      fullPath: '/executive-shield'
      preLoaderRoute: typeof ExecutiveShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/uae-gratuity-calculation': {
      id: '/guides/uae-gratuity-calculation'
      path: '/guides/uae-gratuity-calculation'
      fullPath: '/guides/uae-gratuity-calculation'
      preLoaderRoute: typeof GuidesUaeGratuityCalculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/free-zone-employment-law': {
      id: '/guides/free-zone-employment-law'
      path: '/guides/free-zone-employment-law'
      fullPath: '/guides/free-zone-employment-law'
      preLoaderRoute: typeof GuidesFreeZoneEmploymentLawRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ExecutiveShieldRoute: ExecutiveShieldRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  GuidesFreeZoneEmploymentLawRoute: GuidesFreeZoneEmploymentLawRoute,
  GuidesUaeGratuityCalculationRoute: GuidesUaeGratuityCalculationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
